### ISSUE TITLE
Using F# to extract PNG files from 2007-era XNB game files

### ISSUE THREAD

**Issue by xsyetopz** [nthung-2k5/XnbCli#1]
Hi!

I needed to use `xnbcli` to extract PNG files from a .resources file taken from a game client dated back to mid-2008, but the tool cannot parse such old format. Since I'm also on Linux, [Xnb.Exporter](https://www.nuget.org/packages/Xnb.Exporter) only works on Windows and refuses to work.

I had to manually parse a `Texture2DReader` XNB file and export the PNG. I hope this would help you integrate it in this library using C# so that older XNB formats could be handled.

```fs
module XnbLibrary

open System.IO
open SixLabors.ImageSharp
open SixLabors.ImageSharp.PixelFormats
open SixLabors.ImageSharp.Formats.Png
open System.Resources

type XnbHeader =
    { FileName: string
      Platform: char
      FormatVersion: int
      IsHiDef: bool
      IsCompressed: bool
      FileSize: int
      Readers: {| Type: string; Version: int |} list
      ContentSize: int }

type TextureData =
    { SurfaceFormat: int
      Width: int
      Height: int
      MipLevels: int
      DataSize: int }

let private parseInt32FromBytes =
    function
    | b1 :: b2 :: b3 :: b4 :: _ -> int b1 ||| (int b2 <<< 8) ||| (int b3 <<< 16) ||| (int b4 <<< 24)
    | _ -> 0

let private parse7BitEncodedInteger bytes =
    let rec accumulateValue value shift =
        function
        | currentByte :: remainingBytes ->
            let updatedValue = value ||| ((int (currentByte &&& 0x7Fuy)) <<< shift)

            if (currentByte &&& 0x80uy) = 0uy then
                updatedValue, remainingBytes
            else
                accumulateValue updatedValue (shift + 7) remainingBytes
        | [] -> value, []

    accumulateValue 0 0 bytes

let private detectFileType (bytes: byte list) =
    match bytes with
    | 0x52uy :: 0x49uy :: 0x46uy :: 0x46uy :: _ when
        bytes.Length >= 12
        && bytes.[8] = 0x57uy
        && bytes.[9] = 0x41uy
        && bytes.[10] = 0x56uy
        && bytes.[11] = 0x45uy
        ->
        Some ".wav"
    | 0xFFuy :: 0xFBuy :: _ -> Some ".mp3"
    | 0x4Fuy :: 0x67uy :: 0x67uy :: 0x53uy :: _ -> Some ".ogg"
    | 0x58uy :: 0x4Euy :: 0x42uy :: _ -> Some ".xnb"
    | _ -> None

let private parseXnbHeader (fileName: string) (bytes: byte array) =
    let byteList = bytes |> Array.toList
    let platform = char bytes.[3]
    let formatVersion = int bytes.[4]
    let hidef = (int bytes.[5] &&& 1) = 1
    let compressed = (int bytes.[5] &&& 0x80) = 0x80

    let totalFileSize = parseInt32FromBytes (List.skip 6 byteList)
    let typeReaderCount, remainingData = parse7BitEncodedInteger (List.skip 10 byteList)

    let rec parseTypeReaders remainingCount byteData accumulatedReaders =
        if remainingCount = 0 then
            accumulatedReaders, byteData
        else
            let readerTypeName =
                byteData
                |> List.takeWhile ((<>) 0uy)
                |> List.map char
                |> Array.ofList
                |> System.String
                |> fun path -> if path.StartsWith("/") then path.Substring(1) else path

            let remainingBytes = byteData |> List.skipWhile ((<>) 0uy) |> List.skip 1
            let readerVersion = parseInt32FromBytes remainingBytes

            parseTypeReaders
                (remainingCount - 1)
                (List.skip 4 remainingBytes)
                ((readerTypeName, readerVersion) :: accumulatedReaders)

    let typeReaders, contentStartPosition =
        parseTypeReaders typeReaderCount remainingData []

    let _, finalContentPosition = parse7BitEncodedInteger contentStartPosition

    let contentSize =
        totalFileSize - (List.length byteList - List.length finalContentPosition)

    let header =
        { FileName = fileName
          Platform = platform
          FormatVersion = formatVersion
          IsHiDef = hidef
          IsCompressed = compressed
          FileSize = totalFileSize
          Readers = typeReaders |> List.rev |> List.map (fun (t, v) -> {| Type = t; Version = v |})
          ContentSize = contentSize }

    header, finalContentPosition

let private extractTextureData (bytes: byte list) =
    let parseInt32LittleEndian =
        function
        | b1 :: b2 :: b3 :: b4 :: _ -> (int b4 <<< 24) ||| (int b3 <<< 16) ||| (int b2 <<< 8) ||| int b1
        | _ -> 0

    let surfaceFormat = parseInt32LittleEndian bytes
    let width = parseInt32LittleEndian (List.skip 4 bytes)
    let height = parseInt32LittleEndian (List.skip 8 bytes)
    let mipCount = parseInt32LittleEndian (List.skip 12 bytes)
    let dataSize = parseInt32LittleEndian (List.skip 16 bytes)

    let imageData =
        if List.length bytes >= (20 + dataSize) then
            List.skip 20 bytes |> List.take dataSize
        else
            []

    let info =
        { SurfaceFormat = surfaceFormat
          Width = width
          Height = height
          MipLevels = mipCount
          DataSize = dataSize }

    info, imageData

let private saveTextureAsPng (width: int) (height: int) (imageData: byte list) (outputPath: string) =
    use image = new Image<Rgba32>(width, height)
    let data = Array.ofList imageData

    for y in 0 .. height - 1 do
        for x in 0 .. width - 1 do
            let i = (y * width + x) * 4
            let r = data.[i]
            let g = data.[i + 1]
            let b = data.[i + 2]
            let a = data.[i + 3]
            image[x, y] <- Rgba32(r, g, b, a)

    image.Save(outputPath, new PngEncoder())

let private processResource (outputDir: string) (resourceName: string) (data: obj) =
    match data with
    | :? array<byte> as bytes ->
        let byteList = bytes |> Array.toList

        match detectFileType byteList with
        | Some ext ->
            let outputPath = Path.Combine(outputDir, resourceName + ext)

            match ext with
            | ".xnb" ->
                let header, contentBytes = parseXnbHeader resourceName bytes

                if
                    header.Readers
                    |> List.exists (fun reader -> reader.Type.Contains("Texture2DReader"))
                then
                    let textureInfo, imageData = extractTextureData contentBytes
                    let pngPath = Path.ChangeExtension(outputPath, ".png")
                    saveTextureAsPng textureInfo.Width textureInfo.Height imageData pngPath
                else
                    File.WriteAllBytes(outputPath, bytes)
            | _ -> File.WriteAllBytes(outputPath, bytes)
        | None -> ()
    | _ -> ()

let extractAndExportResources (resourcePath: string) =
    let outputDir = Path.Combine(Path.GetDirectoryName(resourcePath), "extracted")
    Directory.CreateDirectory(outputDir) |> ignore

    use reader = new ResourceReader(resourcePath)
    let enumerator = reader.GetEnumerator()

    while enumerator.MoveNext() do
        let entry = enumerator.Entry
        let key = entry.Key :?> string
        processResource outputDir key entry.Value
```

To test this, simply have an old .resources file, then feed it:
```fs
module Program =
    open XnbLibrary

    [<EntryPoint>]
    let main args =
        let filePath =
            $"<FILE_NAME>.resources"
        extractAndExportResources filePath

        0 // return void
```

**Comment by nthung-2k5** [comment]
It's not that the tool can't extract, it's because of the ".resources" file.
The xnb file is kept inside the resources file as an entry, so I think you should try to save those entries to file with the xnb extension, then run the compiled tool in that folder (I recommend using the sv-1.6 branch).

**Comment by xsyetopz** [comment]
> It's not that the tool can't extract, it's because of the ".resources" file. The xnb file is kept inside the resources file as an entry, so I think you should try to save those entries to file with the xnb extension, then run the compiled tool in that folder (I recommend using the sv-1.6 branch).

That's actually what I did. The instruction said to feed .xnb files over to the 'pack' folder, and it only managed to convert `Effect` into a .cso file that I now have to deal with, but failed on all the textured files. You completely missed what I said, and that's fair enough. The complete code included step-by-step, which is to start from .resources all the way to the PNG files. You obviously will have to opt the .resources part out of it.

```sh
C:\Users\Kasutaja\Desktop\xnbcli-master>xnbcli.exe unpack ".\packed" ".\unpacked"
[INFO] Reading file "packed\approachcircle.xnb" ...
[WARN] XNB Format Version 0x1 unknown.
[INFO] XNB file validated successfully!
[ERROR] Filename: packed\approachcircle.xnb
XnbError: Non-implemented Texture2D format type (1) found.
    at Texture2DReader.read (C:\snapshot\xnbcli\app\Xnb\Readers\Texture2DReader.js:0:0)
    at ReaderResolver.read (C:\snapshot\xnbcli\app\Xnb\ReaderResolver.js:0:0)
    at Xnb.load (C:\snapshot\xnbcli\app\Xnb\index.js:0:0)
    at processUnpack (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.walker.on (C:\snapshot\xnbcli\xnbcli.js:0:0)
    at Walker.emit (events.js:198:13)
    at Object.emitSingleEvents [as emitNodeType] (C:\snapshot\xnbcli\node_modules\walk\lib\node-type-emitter.js:58:13)
    at Walker._wLstatHandler (C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:88:19)
    at C:\snapshot\xnbcli\node_modules\walk\lib\walk.js:106:12
    at FSReqWrap.oncomplete (fs.js:154:5)

[INFO] Reading file "packed\Bloom.xnb" ...
[WARN] XNB Format Version 0x1 unknown.
[INFO] XNB file validated successfully!
[INFO] Successfuly read XNB file!
[INFO] Exporting Effect ...
[INFO] Output file saved: unpacked\Bloom.json
Success 1
Fail 1
```

It's exactly why I had to manually do it (I ran this in a VM)

**Comment by nthung-2k5** [comment]
Could you give an example game that has that problem?

**Comment by xsyetopz** [comment]
> Could you give an example game that has that problem?

I took the .resources from a b337 (2008) client of osu!. You can get it from [here](https://osekai.net/snapshots/?version=84).

**Comment by nthung-2k5** [comment]
I've just pushed a fix.
Try it out.

**Comment by xsyetopz** [comment]
I just did. It worked!

Thank you. If i ever come across another awful .xnb issue, I'll make sure to report it here.
